apiVersion: v1
kind: Pod
metadata:
  name: pvc-inspect
spec:
  containers:
  - name: shell
    image: quay.io/rcardona/walmart-train-demo:latest
    volumeMounts:
    - name: model-storage
      mountPath: /workspace
  volumes:
  - name: model-storage
    persistentVolumeClaim:
      claimName: model-storage
  restartPolicy: Never